# yaml-language-server: $schema=https://raw.githubusercontent.com/Kometa-Team/Kometa/nightly/json-schema/config-schema.json

########################################
# #################################### #
# #  _  _____  __  __ ___ _____ _    # #
# # | |/ / _ \|  \/  | __|_   _/_\   # #
# # | ' < (_) | |\/| | _|  | |/ _ \  # #
# # |_|\_\___/|_|  |_|___| |_/_/ \_\ # #
# #                                  # #
########################################

#==================== sharp_rosalind ====================#
# sharp_rosalind config created by Quickstart on 2026-06-21 17:26:47
# System Information
# OS: Linux 5.15.0-181-generic
# Docker: True
# CPU: Unknown CPU (12 cores)
# Memory: 5675 MB / 31921 MB (17%) | 26246 MB Free
# Python: 3.13.13
# Git: Unavailable
# Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:152.0) Gecko/20100101 Firefox/152.0
# Quickstart Port: 7171
# Quickstart Debug: Disabled
# Quickstart Theme: time
# Quickstart Optimize Template Defaults: Enabled
# Quickstart Config Archive History: Keep all (0)
# Quickstart Kometa Log Retention: Keep all (0)
# Quickstart ImageMaid Log Retention: Keep all (0)
# Quickstart Test Libraries Temp Path: /config/tmp
# Quickstart Test Libraries Install Path: /config/plex_test_libraries
# Quickstart Session Lifetime Days: 30
# Connected to Plex server Homestead version 1.43.2.10687-563d026ea
# Running on Linux version 22.04.5 LTS (Jammy Jellyfish)
# Plex DB cache setting: 1024 MB
# PlexPass: True on Unknown update channel (0).
# Scheduled maintenance running between 23:00 and 6:00
# Quickstart: 0.10.4 | Branch: master | Environment: Docker
###
# Libraries configured with Quickstart: 1 movie, 1 show
# Information on library: Movies
# Type: Movie
# Agent: tv.plex.agents.movie
# Scanner: Plex Movie
# Ratings Source: Rotten Tomatoes
# Content Count: 1023 movies
# 
# Information on library: TV Shows
# Type: Show
# Agent: tv.plex.agents.series
# Scanner: Plex TV Series
# Ratings Source: N/A
# Content Count: 262 shows / 11459 episodes
### 
# We highly recommend using Visual Studio Code with indent-rainbow by oderwat extension and YAML by Red Hat extension. Visual Studio Code will also leverage the above link (yaml-language-server) to enhance Kometa yml edits.
###

# This file is auto-generated by Quickstart. Do not edit manually unless you know what you are doing.
#==================== sharp_rosalind ====================#


#######################################
#  _    _ _                 _         #
# | |  (_) |__ _ _ __ _ _ _(_)___ ___ #
# | |__| | '_ \ '_/ _` | '_| / -_|_-< #
# |____|_|_.__/_| \__,_|_| |_\___/__/ #
#                                     #
#######################################
# validation: validated (last_validated: 2026-06-21 17:26:33)
libraries:
#############################
#  __  __         _         #
# |  \/  |_____ _(_)___ ___ #
# | |\/| / _ \ V / / -_|_-< #
# |_|  |_\___/\_/|_\___/__/ #
#                           #
#############################
  Movies:
    template_variables:
      language: en
#############################################################
#  __  __     _           _      _          ___ _ _         #
# |  \/  |___| |_ __ _ __| |__ _| |_ __ _  | __(_) |___ ___ #
# | |\/| / -_)  _/ _` / _` / _` |  _/ _` | | _|| | / -_|_-< #
# |_|  |_\___|\__\__,_\__,_\__,_|\__\__,_| |_| |_|_\___/__/ #
#                                                           #
#############################################################
    metadata_files:
    - repo: Movies/metadata/movies_mediux.yml
###########################################
#   ___     _ _        _   _              #
#  / __|___| | |___ __| |_(_)___ _ _  ___ #
# | (__/ _ \ | / -_) _|  _| / _ \ ' \(_-< #
#  \___\___/_|_\___\__|\__|_\___/_||_/__/ #
#                                         #
###########################################
    collection_files:
    - default: oscars
      template_variables:
        visible_library: true
        collection_order: release.asc
    - default: cannes
      template_variables:
        visible_library: true
        data:
          starting: latest-10
    - default: razzie
      template_variables:
        visible_library: true
        collection_order: release.asc
        data:
          starting: latest-10
    - default: sundance
      template_variables:
        visible_library: true
    - default: tiff
      template_variables:
        visible_library: true
        collection_order: release.asc
    - default: basic
      template_variables:
        visible_library: true
    - default: other_chart
      template_variables:
        visible_library: true
    - default: universe
      template_variables:
        visible_library: true
    - default: based
    - default: actor
      template_variables:
        style: signature
        exclude:
        - Ryan Reynolds
        - Jack Black
        visible_library: true
        sort_by: title.asc
        data:
          limit: 30
    - default: director
      template_variables:
        style: diiivoycolor
        visible_library: true
        sort_by: title.asc
    - default: writer
      template_variables:
        style: rainier
        visible_library: true
        sort_by: title.asc
    - default: streaming
      template_variables:
        visible_library: true
    - default: seasonal
      template_variables:
        schedule_memorial: range(05/18-06/07)
        visible_library: true
    - default: decade
      template_variables:
        visible_library: true
    - repo: Movies/collections/007.yml
    - repo: Movies/collections/BulletsBombsBabes.yml
    - repo: Movies/collections/DC.yml
    - repo: Movies/collections/Marvel.yml
    - repo: Movies/collections/StarTrek-aired.yml
    - repo: Movies/collections/Tremors.yml
######################################
#   ___              _               #
#  / _ \__ _____ _ _| |__ _ _  _ ___ #
# | (_) \ V / -_) '_| / _` | || (_-< #
#  \___/ \_/\___|_| |_\__,_|\_, /__/ #
#                           |__/     #
######################################
    overlay_files:
    - default: ribbon
    - default: mediastinger
    - default: ratings
      template_variables:
        rating1: user
        rating1_image: rt_tomato
        rating1_font: config/fonts/LibreFranklin-Bold.ttf
        horizontal_position: left
        vertical_position: center
    - default: commonsense
      template_variables:
        horizontal_offset: 0
        vertical_offset: 150
    - default: language_count
    settings:
      asset_directory:
      - /Kometa_assets/Movies
      prioritize_assets: true
    operations:
      assets_for_all: true
      assets_for_all_collections: true
      mass_audience_rating_update:
      - tmdb
      mass_critic_rating_update:
      - imdb
      mass_user_rating_update:
      - mdb_tomatoes
##########################################
#  _______   __  ___ _                   #
# |_   _\ \ / / / __| |_  _____ __ _____ #
#   | |  \ V /  \__ \ ' \/ _ \ V  V (_-< #
#   |_|   \_/   |___/_||_\___/\_/\_//__/ #
#                                        #
##########################################
  TV Shows:
#############################################################
#  __  __     _           _      _          ___ _ _         #
# |  \/  |___| |_ __ _ __| |__ _| |_ __ _  | __(_) |___ ___ #
# | |\/| / -_)  _/ _` / _` / _` |  _/ _` | | _|| | / -_|_-< #
# |_|  |_\___|\__\__,_\__,_\__,_|\__\__,_| |_| |_|_\___/__/ #
#                                                           #
#############################################################
    metadata_files:
    - repo: TV/metadata/Leverage-Redemption.yml
    - repo: TV/metadata/Mutant_X.yml
    - repo: TV/metadata/ST-Enterrpise.yml
###########################################
#   ___     _ _        _   _              #
#  / __|___| | |___ __| |_(_)___ _ _  ___ #
# | (__/ _ \ | / -_) _|  _| / _ \ ' \(_-< #
#  \___\___/_|_\___\__|\__|_\___/_||_/__/ #
#                                         #
###########################################
    collection_files:
    - default: choice
      template_variables:
        visible_library: true
        collection_order: release.asc
    - default: emmy
      template_variables:
        visible_library: true
        collection_order: release.asc
    - default: pca
      template_variables:
        visible_library: true
        collection_order: release.asc
    - default: basic
      template_variables:
        visible_library: true
    - default: other_chart
      template_variables:
        visible_library: true
    - default: universe
      template_variables:
        visible_library: true
        collection_order: release.asc
    - default: based
    - default: actor
      template_variables:
        style: signature
        exclude:
        - Ryan Reynolds
        - Jack Black
        visible_library: true
        sort_by: title.asc
        data:
          limit: 35
    - default: studio
      template_variables:
        visible_library: true
    - default: decade
      template_variables:
        visible_library: true
    - repo: TV/collections/StarTrek-aired.yml
######################################
#   ___              _               #
#  / _ \__ _____ _ _| |__ _ _  _ ___ #
# | (_) \ V / -_) '_| / _` | || (_-< #
#  \___/ \_/\___|_| |_\__,_|\_, /__/ #
#                           |__/     #
######################################
    overlay_files:
    - default: ribbon
    - default: status
      template_variables:
        back_color_airing: '#016920FF'
        back_color_returning: '#81007FFF'
        back_color_canceled: '#B52222FF'
        back_color_ended: '#000847FF'
    - default: ratings
      template_variables:
        rating1: user
        rating1_image: rt_tomato
        rating1_font: config/fonts/LibreFranklin-Bold.ttf
        horizontal_position: left
        vertical_position: center
    - default: commonsense
      template_variables:
        horizontal_offset: 0
        vertical_offset: 150
    - default: language_count
    - default: language_count
      template_variables:
        builder_level: season
    - default: language_count
      template_variables:
        builder_level: episode
    settings:
      asset_directory:
      - /Kometa_assets/TV
      prioritize_assets: true
    operations:
      assets_for_all: true
      assets_for_all_collections: true
      mass_audience_rating_update:
      - tmdb
      mass_critic_rating_update:
      - imdb
      mass_user_rating_update:
      - mdb_tomatoes

###################################
#  ___ _           _ _    _       #
# | _ \ |__ _ _  _| (_)__| |_ ___ #
# |  _/ / _` | || | | (_-<  _(_-< #
# |_| |_\__,_|\_, |_|_/__/\__/__/ #
#             |__/                #
###################################
playlist_files:
- default: playlist
  template_variables:
    libraries:
    - Movies
    - TV Shows

#####################################
#  ___      _   _   _               #
# / __| ___| |_| |_(_)_ _  __ _ ___ #
# \__ \/ -_)  _|  _| | ' \/ _` (_-< #
# |___/\___|\__|\__|_|_||_\__, /__/ #
#                         |___/     #
#####################################
# validation: validated (last_validated: 2026-06-21 17:26:34)
settings:
  asset_depth: 4
  asset_directory: []
  asset_folders: true
  cache: true
  cache_expiration: 60
  create_asset_folders: true
  custom_repo: https://raw.githubusercontent.com/cmattogno/kometa-custom/main/
  default_collection_order: release
  delete_below_minimum: false
  delete_not_scheduled: false
  dimensional_asset_rename: true
  download_url_assets: true
  ignore_ids:
  ignore_imdb_ids:
  item_refresh_delay: 0
  minimum_items: 2
  missing_only_released: true
  only_filter_missing: true
  overlay_artwork_filetype: png
  overlay_artwork_quality: 90
  playlist_exclude_users:
  playlist_report: true
  playlist_sync_to_users:
  prioritize_assets: true
  run_again_delay: 4
  run_order:
  - operations
  - metadata
  - overlays
  - collections
  save_report: true
  show_asset_not_needed: true
  show_filtered: true
  show_missing: false
  show_missing_assets: true
  show_missing_episode_assets: false
  show_missing_season_assets: false
  show_options: true
  show_unconfigured: true
  show_unfiltered: true
  show_unmanaged: true
  sync_mode: sync
  tvdb_language: eng
  verify_ssl: true

###################
#  ___ _          #
# | _ \ |_____ __ #
# |  _/ / -_) \ / #
# |_| |_\___/_\_\ #
#                 #
###################
# validation: validated (last_validated: 2026-06-21 17:26:30)
plex:
  clean_bundles: true
  db_cache: 1024
  empty_trash: true
  optimize: true
  timeout: 60
  token: (redacted)
  url: (redacted)
  verify_ssl: true

############################
#  _____ __  __ ___  _     #
# |_   _|  \/  |   \| |__  #
#   | | | |\/| | |) | '_ \ #
#   |_| |_|  |_|___/|_.__/ #
#                          #
############################
# validation: validated (last_validated: 2026-06-21 17:26:31)
tmdb:
  apikey: (redacted)
  cache_expiration: 60
  language: en
  region: US

###################################
#  _____          _        _ _ _  #
# |_   _|_ _ _  _| |_ _  _| | (_) #
#   | |/ _` | || |  _| || | | | | #
#   |_|\__,_|\_,_|\__|\_,_|_|_|_| #
#                                 #
###################################
# validation: validated (last_validated: 2026-06-21 17:26:31)
tautulli:
  apikey: (redacted)
  url: (redacted)

###############################
#   ___ _ _   _  _      _     #
#  / __(_) |_| || |_  _| |__  #
# | (_ | |  _| __ | || | '_ \ #
#  \___|_|\__|_||_|\_,_|_.__/ #
#                             #
###############################
# validation: validated (last_validated: 2026-06-21 17:26:31)
github:
  token: (redacted)

###################################
#  __  __ ___  ___ _    _    _    #
# |  \/  |   \| _ ) |  (_)__| |_  #
# | |\/| | |) | _ \ |__| (_-<  _| #
# |_|  |_|___/|___/____|_/__/\__| #
#                                 #
###################################
# validation: validated (last_validated: 2026-06-21 17:26:32)
mdblist:
  apikey: (redacted)
  cache_expiration: 60

################################
#  ___         _               #
# | _ \__ _ __| |__ _ _ _ _ _  #
# |   / _` / _` / _` | '_| '_| #
# |_|_\__,_\__,_\__,_|_| |_|   #
#                              #
################################
# validation: validated (last_validated: 2026-06-21 17:26:32)
radarr:
  add_existing: false
  add_missing: false
  availability: announced
  ignore_cache: false
  monitor: true
  monitor_existing: false
  plex_path:
  quality_profile: Homestead Preferred
  radarr_path:
  root_folder_path: /movies
  search: false
  tag:
  token: (redacted)
  upgrade_existing: false
  url: (redacted)

################################
#  ___                         #
# / __| ___ _ _  __ _ _ _ _ _  #
# \__ \/ _ \ ' \/ _` | '_| '_| #
# |___/\___/_||_\__,_|_| |_|   #
#                              #
################################
# validation: validated (last_validated: 2026-06-21 17:26:33)
sonarr:
  add_existing: false
  add_missing: false
  cutoff_search: false
  ignore_cache: false
  language_profile: English
  monitor: all
  monitor_existing: false
  plex_path:
  quality_profile: Homestead Preferred
  root_folder_path: /tv_03
  search: false
  season_folder: true
  series_type: standard
  sonarr_path:
  tag:
  token: (redacted)
  upgrade_existing: false
  url: (redacted)

###########################
#  _____         _   _    #
# |_   _| _ __ _| |_| |_  #
#   | || '_/ _` | / /  _| #
#   |_||_| \__,_|_\_\\__| #
#                         #
###########################
# validation: validated (last_validated: 2026-06-21 17:26:34)
trakt:
  authorization:
    access_token: (redacted)
    created_at: '1781786652'
    expires_in: 604799
    refresh_token: (redacted)
    scope: public
    token_type: Bearer
  client_id: (redacted)
  client_secret: (redacted)
  pin:
  force_refresh: false
