Auth:
    Enabled: true
    Password: $argon2id$[REDACTED]
Logging:
    Level: INFO
MediaServer:
    Type: Plex
    URL: https://[REDACTED].plex.direct:32400
    ApiToken: [REDACTED]
    Libraries:
        - Title: Movies
        - Title: TV Shows
    EnableSortByEpisodeAddedDate: true
    EnablePlexEventListener: false
Mediux:
    ApiToken: [REDACTED]
    DownloadQuality: optimized
AutoDownload:
    Enabled: true
    Cron: 0 0 * * *
Images:
    CacheImages:
        Enabled: true
    SaveImagesLocally:
        Enabled: true
        Path: /Kometa_assets
        EpisodeNamingConvention: static
LabelsAndTags:
    Applications:
        - Application: Sonarr
          Enabled: true
          Add:
            - aura
        - Application: Radarr
          Enabled: true
          Add:
            - aura
SonarrRadarr:
    Applications:
        - Type: Sonarr
          Library: TV Shows
          URL: http://sonarr:8989
          ApiToken: [REDACTED]
        - Type: Radarr
          Library: Movies
          URL: http://radarr:7878
          ApiToken: [REDACTED]
Database:
    Type: sqlite3
    Path: AURA.db
